baseURL = "https://leandrocp.com.br/"
languageCode = "en-us"
title = "Leandro Cesquini Pereira"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-60912157-1"

[params]
    theme_color = "#4b285b"
    description = "Leandro Cesquini Pereira. Software Engineer and Open Source contributor"
    description_photo = "leandro.jpeg"
    favicon = "favicon.ico"
    twitter = "leandrocesquini"
    linkedin = "https://www.linkedin.com/in/leandrocesquini"
    medium = "leandrocesquini"
    github = "leandrocp"

[params.nav]
    enable = false

[params.hero]
    enable = true
    avatar = "leandro.jpeg"
    subtitle = "Hi! I'm Leandro. A software engineer & open source contributor."